version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: name
      MONGO_INITDB_ROOT_PASSWORD: pass
  # for mongo gui - optional
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: name
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
  # for redis gui - optional
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: "redis-commander"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
  url_shortener:
    container_name: url_shortener_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_HOST: mongodb
      REDIS_HOST: redis
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - redis
volumes:
  mongodb_data:
