spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  data:
    mongodb:
      #uri: mongodb://root:password@localhost:27017/?authSource=admin
      host: ${MONGO_HOST:localhost}
      port: 27017
      username: name
      password: pass
      database: urls
      authentication-database: admin
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
  cache:
    type: redis
redis:
  ttl: 2
